eureka:
  client:
    service-url:
      defaultZone: http://wyl:123@localhost:8761/eureka,http://wyl2:456@localhost:8762/eureka
spring:
  application:
    name: CUSTOMER
server:
  port: 8080

#指定具体服务的负载均衡策略
SEARCH:
  ribbon:
    #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule