server:
  port: 8762

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
        http://wyl:123@${eureka.instance.hostname}:8761/eureka
    registry-fetch-interval-seconds: 15
  server:
    enable-self-preservation: true

spring:
  security:
    user:
      name: wyl2
      password: 456
  application:
    name: SERVER2
